// Do not modify this file, it was automatically generated by CMake.

#ifndef CONFIG_H_
#define CONFIG_H_

#define HAVE_STRCASECMP

#define HAVE_STRNCASECMP

/* #undef HAVE_STRTOKS */
#ifdef HAVE_STRTOKS
// strtok_s is the actual C11 standard rather than posix strtok_r
// but its also an optional standard, MSVC supports it, so alias it
#define HAVE_STRTOKR
#define strtok_r strtok_s
#else
#define HAVE_STRTOKR       // spelled oddly to differ from wx's similar test
#endif

// Handle platform differences in math.h
#define HAVE_MATH_H

// Handle platform differences in C++ cmath.
#define HAVE_CXX_CMATH

#define HAVE_CMATH_ASINH

#define HAVE_CMATH_ACOSH

#define HAVE_CMATH_ATANH

#define HAVE_CMATH_ISINF

#if !defined( HAVE_CLOCK_GETTIME )
#define HAVE_CLOCK_GETTIME
#endif

#define HAVE_GETTIMEOFDAY_FUNC

#define MALLOC_IN_STDLIB_H

#if !defined( MALLOC_IN_STDLIB_H )
#include <malloc.h>
#endif

#define HAVE_ISO646_H

#if defined( HAVE_ISO646_H )
#include <iso646.h>
#endif

#if !defined( HAVE_STRCASECMP )
#define strcasecmp stricmp
#endif

#if !defined( HAVE_STRNCASECMP )
#define strncasecmp strnicmp
#endif

// Does the compiler support the -Wunused-const-variable warning
#define HAVE_WUNUSED_CONST_VARIABLE

// Does the compiler support the -Wimplicit-int-float-conversion warning
/* #undef HAVE_WIMPLICIT_FLOAT_CONVERSION */

// Does the compiler support the -Winconsistent-missing-override
/* #undef HAVE_WINCONSISTENT_MISSING_OVERRIDE */

// Use Posix getc_unlocked() instead of getc() when it's available.
#define HAVE_FGETC_NOLOCK

// Warning!!!  Using wxGraphicContext for rendering is experimental.
/* #undef USE_WX_GRAPHICS_CONTEXT */

/// The legacy file format revision of the *.brd file created by this build
#define LEGACY_BOARD_FILE_VERSION       2

/// The install prefix defined during CMake configuration or fall back to CMAKE_INSTALL_PREFIX.
#define DEFAULT_INSTALL_PATH            "/opt/kicad"

/// The wxPython version found during configuration.
#if defined( KICAD_SCRIPTING_WXPYTHON )
#define WXPYTHON_VERSION                "4.2.0"
#endif

#define PYTHON_VERSION_MAJOR             3
#define PYTHON_VERSION_MINOR             10

/// A file extension with a leading '.' is a suffix, and this one is used on
/// top level program modules which implement the KIFACE.
#define KIFACE_SUFFIX                   ".kiface"
#define KIFACE_PREFIX                   "_"

/// Allows scripts install directory to be referenced by the program code.
#define PYTHON_DEST                     "local/lib/python3.10/dist-packages"

#define PYTHON_SITE_PACKAGE_PATH        "local/lib/python3.10/dist-packages"

/// Allows scripts install directory to be referenced by the program code.
#define KICAD_DATA                      "/opt/kicad/share/kicad"

/// Allows KiCad stock EDA library data (templates, symbols, footprints, 3dmodels)
/// directory to be referenced by the program code.
#define KICAD_LIBRARY_DATA              "/opt/kicad/share/kicad"

/// Allows documentation install directory to be referenced by the program code.
#define KICAD_DOCS                      "/opt/kicad/share/doc/kicad"

// Plugins directory
#define KICAD_PLUGINDIR                 "/opt/kicad/lib"

/// ngspice version string detected by pkg-config when available.
#define NGSPICE_BUILD_VERSION      "42"

/// When pkg-config config is not available for ngspice, use ngspice/config.h for version.
/* #undef NGSPICE_HAVE_CONFIG_H */

/// Path to the python executable that should be used by KiCad
#define PYTHON_EXECUTABLE               "/usr/bin/python3"

#endif  // CONFIG_H_
