/* Do not modify this file, it was automatically generated by CMake. */

/*
 * Define the KiCad build version strings.
 */
#ifndef __KICAD_VERSION_H__
#define __KICAD_VERSION_H__

#ifndef INCLUDE_KICAD_VERSION
#error Do not include kicad_build_version.h directly.  Include build_version.h instead.
#endif

#define KICAD_COMMIT_HASH               "af02650689f2795aba44f2a396a107854fdecc9b"
#define KICAD_VERSION_FULL              "8.0.0-rc3-60-gaf02650689"
#define KICAD_SEMANTIC_VERSION          "8.0.0~rc3"
#define KICAD_MAJOR_VERSION             "8"
#define KICAD_MINOR_VERSION             "0"
#define KICAD_PATCH_VERSION             "0"
#define KICAD_IS_NIGHTLY                0
#define KICAD_MAJOR_MINOR_VERSION       "8.0"
#define KICAD_MAJOR_MINOR_PATCH_VERSION "8.0.0"
#define KICAD_MAJOR_MINOR_PATCH_TUPLE   { 8, 0, 0 }
#define KICAD_WIN32_RC_PRODVER          8, 0, 0, 36729
#define KICAD_WIN32_RC_PRODVER_STR      "8.0.0\0"
#define KICAD_WIN32_RC_FILEVER          8, 0, 0, 36729
#define KICAD_WIN32_RC_FILEVER_STR      "8.0.0.36729\0"

#endif  /* __KICAD_VERSION_H__ */
